### ISSUE TITLE
How to capture selected values

### ISSUE THREAD

**Issue by daviddelmonte** [YahyaBagia/YBTextPicker#1]
Can you please let me know how to select single or multiple values? Many thanks

**Comment by YahyaBagia** [comment]
Hey @daviddelmonte, did you check the examples in [ViewController.swift](https://github.com/YahyaBagia/YBTextPicker/blob/master/YBTextPicker/ViewController.swift) ?

```onCompletion``` handler of ```init``` method gets executed upon clicking ```done``` button. It provides you with ```selectedValues``` and ```selectedIndexes``` arrays. In case of single selection, these arrays will contain single objects.

**Comment by daviddelmonte** [comment]
I’m sorry, I should’ve closed the issue. Thanks for posting.
